version: "3.0"
services:
  vrp :
    image : vrp-api
    container_name:  vrp-api
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE : qa
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vrp-qa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
  mysql :
    image : mysql
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vrp-qa
      LANG: C.UTF_8
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: